### ISSUE TITLE
The start script is not running

### ISSUE THREAD

**Issue by Rishabh2801** [nahuelcandia/mobile-app-maker#1]
It throws error: 

```
$ ./start.sh
internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module 'express'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (C:\Users\Rishabh\mobile-app-maker\server.js:43:11)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
   at Function.Module._load (internal/modules/cjs/loader.js:530:3)
```

**Comment by daddyparodz** [comment]
npm install

**Comment by ghost** [comment]
some dependencies are not installing
